# Week2授業前課題3

# 【課題1】内積を手計算しよう
以下の行列A,Bの内積を手計算する。

$A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 \\
      7 & 8 & -9
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
      0 & 2 & 1 \\
      0 & 2 & -8 \\
      2 & 9 & -1
    \end{array}
  \right]$
  
  $(1, 1)= -1 \times 0 + 2 \times 0 + 3 \times 2 = 6$
  
  $(1, 2)= -1 \times 2 + 2 \times 2 + 3 \times 9 = 29$
  
  $(1, 3)= -1 \times 1 + 2 \times -8 + 3 \times -1 = -20$
  
  $(2, 1)= 4 \times 0 + -5 \times 0 + 6 \times 2 = 12$
  
  $(2, 2)= 4 \times 2 + -5 \times 2 + 6 \times 9 = 52$
  
  $(2, 3)= 4 \times 1 + -5 \times -8 + 6 \times -1 = 38$
  
  $(3, 1)= 7 \times 0 + 8 \times 0 + -9 \times 2 = -18$
  
  $(3, 2)= 7 \times 2 + 8 \times 2 + -9 \times 9 = -51$
  
  $(3, 3)= 7 \times 1 + 8 \times -8 + -9 \times -1 = -48$

$ = \begin{pmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48& \\ \end{pmatrix} $


# 【課題2】1次元配列の内積をfor文で計算しよう
【課題1】の行列のうち下記をNumPyを使って解く

配列のindexを指定し、

* 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
* 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
* 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる   
それらの値を全て足し合わせる

In [1]:
import numpy as np

# 行列Aを作成
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
# 行列Bを作成
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 計算結果格納用
ans = 0

# Aの1行目とBの1列目を計算
for i in range(3):
    ans = ans + A[0][i] * B[i][0]

print(ans)

6


# 【課題3】多次元配列の内積をfor文で計算しよう
【課題1】の行列の内積を全て計算する

In [2]:
# 計算結果格納用
AB = np.zeros((3, 3))

# 各内積を計算
for col in range(3):       # Aの行を指定
    for row in range(3): # Bの列を指定
        for i in range(3):   # 要素数分回す
            AB[col][row] += A[col][i] * B[i][row]
            
print(AB)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 【課題4】内積をnp.dotで計算しよう
【課題1】の行列の内積をnp.dotで計算しよう

In [3]:
AB = np.dot(A, B)

print(AB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【課題5】内積ができないときはどうするか
下記の配列の内積を計算しようとすると、エラーが出る
$A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4 
    \end{array}
  \right]$
  

In [4]:
# 行列Aを作成
A = np.array([[-1, 2, 3], [4, -5, 6]])
# 行列Bを作成
B = np.array([[-9, 8, 7], [6, -5, 4]])

# エラーで止まってしまうため、コメントアウト
# AB = np.dot(A, B)

np.dotを実行すると下記エラーが発生する

ValueError                                Traceback (most recent call last)<br>
<ipython-input-4-40f2ec9bbfb2> in <module>　　<br>
      4 B = np.array([[-9, 8, 7], [6, -5, 4]])　　<br>
      5 　　<br>
----> 6 AB = np.dot(A, B)　　<br>
      7 　　<br>
      8 print(AB)　　<br>
　　<br>
ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)


上記は内積できる行列の形状には条件があり、  
掛け合わせる片方の行列の列数 と もう片方の行列の行数  
が一致している必要があるために発生する。

今回のケースでいえばA・Bそれぞれが2×3の行列であるため、  
2×3行列と3×2行列にする操作が必要となる。  
例)行列Bを転置

$A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4 
    \end{array}
  \right]$
  
                                    ↓
  
$A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
       -9 & 8 \\
       7 & 6 \\
      6 & -5 
    \end{array}
  \right]$

この操作を転置といい、下記のように転置ができる。

In [8]:
# 行列Bを転置(Transpose)
B = B.T

print(A)
print(B)

[[-1  2  3]
 [ 4 -5  6]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]


行列Aが2×3
行列Bが3×2
になったため、np.dotで計算が可能になる

In [6]:
AB = np.dot(A, B)

print(AB)

[[ 46  -4]
 [-34  73]]
