## 【問題1】SimpleRNNのフォワードプロパゲーション実装
- numpyなどの最低限のライブラリで実装

In [0]:
import numpy as np


class SimpleRNN:
    """
    シンプル構造のRNN
    Parameters
    ----------
    W : ndarray
      入力に対する重み
    U : ndarray
      状態に対する重み
    B : ndarray
      バイアス項
    """
    def __init__(self, W, U, B):
        self.W = W
        self.U = U
        self.B = B
        self.n_node = self.W.shape[1]

    def forward(self, X):
        """
        フォワード
        Parameters
        ----------
        X : 次の形のndarray, shape (batch_size, n_sequences, n_features)
            入力
        Returns
        ----------
        S : 次の形のndarray, shape (batch_size, n_sequences, n_node)
            出力
        """
        
        batch_size = x.shape[0]
        n_sequences = x.shape[1]
        
        S= np.zeros((batch_size, n_sequences, self.n_node))
        
        for t in range(n_sequences):
            S[:, t, :] = np.tanh(X[:, t, :].dot(self.W) + S[:, t - 1, :].dot(self.U) + self.B)

        return S

## 【問題2】小さな配列でのフォワードプロパゲーションの実験

In [0]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes))
b = np.array([1])

srnn = SimpleRNN(w_x, w_h, b)
hoge = srnn.forward(x)
print(hoge)

[[[0.76188798 0.76213958 0.76239095 0.76255841]
  [0.792209   0.8141834  0.83404912 0.84977719]
  [0.79494228 0.81839002 0.83939649 0.85584174]]]


## 【問題3】（アドバンス課題）バックプロパゲーションの実装